# Generated by Django 4.1 on 2022-10-20 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ln_nodes',
            name='address',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='ln_nodes',
            name='macaroon_path',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='ln_nodes',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ln_nodes',
            name='tls_path',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entities',
            name='contracts',
            field=models.ManyToManyField(blank=True, null=True, to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='ln_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.ln_nodes'),
        ),
    ]
