# Generated by Django 4.1 on 2022-10-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_ln_nodes_address_ln_nodes_macaroon_path_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entities',
            new_name='Entity',
        ),
        migrations.RenameModel(
            old_name='LN_Nodes',
            new_name='LN_Node',
        ),
    ]
