# Generated by Django 4.1 on 2022-10-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_good_service_saleofservice_saleofgood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='contracts',
            field=models.ManyToManyField(blank=True, to='contracts.contract'),
        ),
    ]
