# Generated by Django 4.1 on 2022-10-21 00:54

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_entity_contracts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ln_node',
            name='macaroon_path',
            field=models.FileField(upload_to=contracts.models.LN_Node.ln_node_dir),
        ),
        migrations.AlterField(
            model_name='ln_node',
            name='tls_path',
            field=models.FileField(upload_to=contracts.models.LN_Node.ln_node_dir),
        ),
    ]
