# Generated by Django 4.1.2 on 2022-11-04 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_ln_node_macaroon_path_alter_ln_node_tls_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='monetaryobligation',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.entity'),
        ),
    ]
